//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteAsmx.ServicoDeDados {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Pessoa", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Pessoa : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        private System.DateTime DataNascimentoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public System.DateTime DataNascimento {
            get {
                return this.DataNascimentoField;
            }
            set {
                if ((this.DataNascimentoField.Equals(value) != true)) {
                    this.DataNascimentoField = value;
                    this.RaisePropertyChanged("DataNascimento");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicoDeDados.PessoasServiceSoap")]
    public interface PessoasServiceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        ClienteAsmx.ServicoDeDados.HelloWorldResponse HelloWorld(ClienteAsmx.ServicoDeDados.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<ClienteAsmx.ServicoDeDados.HelloWorldResponse> HelloWorldAsync(ClienteAsmx.ServicoDeDados.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name nome from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConverterParaMaiusculas", ReplyAction="*")]
        ClienteAsmx.ServicoDeDados.ConverterParaMaiusculasResponse ConverterParaMaiusculas(ClienteAsmx.ServicoDeDados.ConverterParaMaiusculasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConverterParaMaiusculas", ReplyAction="*")]
        System.Threading.Tasks.Task<ClienteAsmx.ServicoDeDados.ConverterParaMaiusculasResponse> ConverterParaMaiusculasAsync(ClienteAsmx.ServicoDeDados.ConverterParaMaiusculasRequest request);
        
        // CODEGEN: Generating message contract since element name nome from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObterPessoaPorNome", ReplyAction="*")]
        ClienteAsmx.ServicoDeDados.ObterPessoaPorNomeResponse ObterPessoaPorNome(ClienteAsmx.ServicoDeDados.ObterPessoaPorNomeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObterPessoaPorNome", ReplyAction="*")]
        System.Threading.Tasks.Task<ClienteAsmx.ServicoDeDados.ObterPessoaPorNomeResponse> ObterPessoaPorNomeAsync(ClienteAsmx.ServicoDeDados.ObterPessoaPorNomeRequest request);
        
        // CODEGEN: Generating message contract since element name pessoa from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObterNomePessoaEmMaiusculo", ReplyAction="*")]
        ClienteAsmx.ServicoDeDados.ObterNomePessoaEmMaiusculoResponse ObterNomePessoaEmMaiusculo(ClienteAsmx.ServicoDeDados.ObterNomePessoaEmMaiusculoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObterNomePessoaEmMaiusculo", ReplyAction="*")]
        System.Threading.Tasks.Task<ClienteAsmx.ServicoDeDados.ObterNomePessoaEmMaiusculoResponse> ObterNomePessoaEmMaiusculoAsync(ClienteAsmx.ServicoDeDados.ObterNomePessoaEmMaiusculoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public ClienteAsmx.ServicoDeDados.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(ClienteAsmx.ServicoDeDados.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClienteAsmx.ServicoDeDados.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(ClienteAsmx.ServicoDeDados.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConverterParaMaiusculasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConverterParaMaiusculas", Namespace="http://tempuri.org/", Order=0)]
        public ClienteAsmx.ServicoDeDados.ConverterParaMaiusculasRequestBody Body;
        
        public ConverterParaMaiusculasRequest() {
        }
        
        public ConverterParaMaiusculasRequest(ClienteAsmx.ServicoDeDados.ConverterParaMaiusculasRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConverterParaMaiusculasRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nome;
        
        public ConverterParaMaiusculasRequestBody() {
        }
        
        public ConverterParaMaiusculasRequestBody(string nome) {
            this.nome = nome;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConverterParaMaiusculasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConverterParaMaiusculasResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClienteAsmx.ServicoDeDados.ConverterParaMaiusculasResponseBody Body;
        
        public ConverterParaMaiusculasResponse() {
        }
        
        public ConverterParaMaiusculasResponse(ClienteAsmx.ServicoDeDados.ConverterParaMaiusculasResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConverterParaMaiusculasResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ConverterParaMaiusculasResult;
        
        public ConverterParaMaiusculasResponseBody() {
        }
        
        public ConverterParaMaiusculasResponseBody(string ConverterParaMaiusculasResult) {
            this.ConverterParaMaiusculasResult = ConverterParaMaiusculasResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObterPessoaPorNomeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObterPessoaPorNome", Namespace="http://tempuri.org/", Order=0)]
        public ClienteAsmx.ServicoDeDados.ObterPessoaPorNomeRequestBody Body;
        
        public ObterPessoaPorNomeRequest() {
        }
        
        public ObterPessoaPorNomeRequest(ClienteAsmx.ServicoDeDados.ObterPessoaPorNomeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObterPessoaPorNomeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nome;
        
        public ObterPessoaPorNomeRequestBody() {
        }
        
        public ObterPessoaPorNomeRequestBody(string nome) {
            this.nome = nome;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObterPessoaPorNomeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObterPessoaPorNomeResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClienteAsmx.ServicoDeDados.ObterPessoaPorNomeResponseBody Body;
        
        public ObterPessoaPorNomeResponse() {
        }
        
        public ObterPessoaPorNomeResponse(ClienteAsmx.ServicoDeDados.ObterPessoaPorNomeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObterPessoaPorNomeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ClienteAsmx.ServicoDeDados.Pessoa ObterPessoaPorNomeResult;
        
        public ObterPessoaPorNomeResponseBody() {
        }
        
        public ObterPessoaPorNomeResponseBody(ClienteAsmx.ServicoDeDados.Pessoa ObterPessoaPorNomeResult) {
            this.ObterPessoaPorNomeResult = ObterPessoaPorNomeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObterNomePessoaEmMaiusculoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObterNomePessoaEmMaiusculo", Namespace="http://tempuri.org/", Order=0)]
        public ClienteAsmx.ServicoDeDados.ObterNomePessoaEmMaiusculoRequestBody Body;
        
        public ObterNomePessoaEmMaiusculoRequest() {
        }
        
        public ObterNomePessoaEmMaiusculoRequest(ClienteAsmx.ServicoDeDados.ObterNomePessoaEmMaiusculoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObterNomePessoaEmMaiusculoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ClienteAsmx.ServicoDeDados.Pessoa pessoa;
        
        public ObterNomePessoaEmMaiusculoRequestBody() {
        }
        
        public ObterNomePessoaEmMaiusculoRequestBody(ClienteAsmx.ServicoDeDados.Pessoa pessoa) {
            this.pessoa = pessoa;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObterNomePessoaEmMaiusculoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObterNomePessoaEmMaiusculoResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClienteAsmx.ServicoDeDados.ObterNomePessoaEmMaiusculoResponseBody Body;
        
        public ObterNomePessoaEmMaiusculoResponse() {
        }
        
        public ObterNomePessoaEmMaiusculoResponse(ClienteAsmx.ServicoDeDados.ObterNomePessoaEmMaiusculoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObterNomePessoaEmMaiusculoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ClienteAsmx.ServicoDeDados.Pessoa ObterNomePessoaEmMaiusculoResult;
        
        public ObterNomePessoaEmMaiusculoResponseBody() {
        }
        
        public ObterNomePessoaEmMaiusculoResponseBody(ClienteAsmx.ServicoDeDados.Pessoa ObterNomePessoaEmMaiusculoResult) {
            this.ObterNomePessoaEmMaiusculoResult = ObterNomePessoaEmMaiusculoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PessoasServiceSoapChannel : ClienteAsmx.ServicoDeDados.PessoasServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PessoasServiceSoapClient : System.ServiceModel.ClientBase<ClienteAsmx.ServicoDeDados.PessoasServiceSoap>, ClienteAsmx.ServicoDeDados.PessoasServiceSoap {
        
        public PessoasServiceSoapClient() {
        }
        
        public PessoasServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PessoasServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PessoasServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PessoasServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteAsmx.ServicoDeDados.HelloWorldResponse ClienteAsmx.ServicoDeDados.PessoasServiceSoap.HelloWorld(ClienteAsmx.ServicoDeDados.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            ClienteAsmx.ServicoDeDados.HelloWorldRequest inValue = new ClienteAsmx.ServicoDeDados.HelloWorldRequest();
            inValue.Body = new ClienteAsmx.ServicoDeDados.HelloWorldRequestBody();
            ClienteAsmx.ServicoDeDados.HelloWorldResponse retVal = ((ClienteAsmx.ServicoDeDados.PessoasServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteAsmx.ServicoDeDados.HelloWorldResponse> ClienteAsmx.ServicoDeDados.PessoasServiceSoap.HelloWorldAsync(ClienteAsmx.ServicoDeDados.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteAsmx.ServicoDeDados.HelloWorldResponse> HelloWorldAsync() {
            ClienteAsmx.ServicoDeDados.HelloWorldRequest inValue = new ClienteAsmx.ServicoDeDados.HelloWorldRequest();
            inValue.Body = new ClienteAsmx.ServicoDeDados.HelloWorldRequestBody();
            return ((ClienteAsmx.ServicoDeDados.PessoasServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteAsmx.ServicoDeDados.ConverterParaMaiusculasResponse ClienteAsmx.ServicoDeDados.PessoasServiceSoap.ConverterParaMaiusculas(ClienteAsmx.ServicoDeDados.ConverterParaMaiusculasRequest request) {
            return base.Channel.ConverterParaMaiusculas(request);
        }
        
        public string ConverterParaMaiusculas(string nome) {
            ClienteAsmx.ServicoDeDados.ConverterParaMaiusculasRequest inValue = new ClienteAsmx.ServicoDeDados.ConverterParaMaiusculasRequest();
            inValue.Body = new ClienteAsmx.ServicoDeDados.ConverterParaMaiusculasRequestBody();
            inValue.Body.nome = nome;
            ClienteAsmx.ServicoDeDados.ConverterParaMaiusculasResponse retVal = ((ClienteAsmx.ServicoDeDados.PessoasServiceSoap)(this)).ConverterParaMaiusculas(inValue);
            return retVal.Body.ConverterParaMaiusculasResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteAsmx.ServicoDeDados.ConverterParaMaiusculasResponse> ClienteAsmx.ServicoDeDados.PessoasServiceSoap.ConverterParaMaiusculasAsync(ClienteAsmx.ServicoDeDados.ConverterParaMaiusculasRequest request) {
            return base.Channel.ConverterParaMaiusculasAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteAsmx.ServicoDeDados.ConverterParaMaiusculasResponse> ConverterParaMaiusculasAsync(string nome) {
            ClienteAsmx.ServicoDeDados.ConverterParaMaiusculasRequest inValue = new ClienteAsmx.ServicoDeDados.ConverterParaMaiusculasRequest();
            inValue.Body = new ClienteAsmx.ServicoDeDados.ConverterParaMaiusculasRequestBody();
            inValue.Body.nome = nome;
            return ((ClienteAsmx.ServicoDeDados.PessoasServiceSoap)(this)).ConverterParaMaiusculasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteAsmx.ServicoDeDados.ObterPessoaPorNomeResponse ClienteAsmx.ServicoDeDados.PessoasServiceSoap.ObterPessoaPorNome(ClienteAsmx.ServicoDeDados.ObterPessoaPorNomeRequest request) {
            return base.Channel.ObterPessoaPorNome(request);
        }
        
        public ClienteAsmx.ServicoDeDados.Pessoa ObterPessoaPorNome(string nome) {
            ClienteAsmx.ServicoDeDados.ObterPessoaPorNomeRequest inValue = new ClienteAsmx.ServicoDeDados.ObterPessoaPorNomeRequest();
            inValue.Body = new ClienteAsmx.ServicoDeDados.ObterPessoaPorNomeRequestBody();
            inValue.Body.nome = nome;
            ClienteAsmx.ServicoDeDados.ObterPessoaPorNomeResponse retVal = ((ClienteAsmx.ServicoDeDados.PessoasServiceSoap)(this)).ObterPessoaPorNome(inValue);
            return retVal.Body.ObterPessoaPorNomeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteAsmx.ServicoDeDados.ObterPessoaPorNomeResponse> ClienteAsmx.ServicoDeDados.PessoasServiceSoap.ObterPessoaPorNomeAsync(ClienteAsmx.ServicoDeDados.ObterPessoaPorNomeRequest request) {
            return base.Channel.ObterPessoaPorNomeAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteAsmx.ServicoDeDados.ObterPessoaPorNomeResponse> ObterPessoaPorNomeAsync(string nome) {
            ClienteAsmx.ServicoDeDados.ObterPessoaPorNomeRequest inValue = new ClienteAsmx.ServicoDeDados.ObterPessoaPorNomeRequest();
            inValue.Body = new ClienteAsmx.ServicoDeDados.ObterPessoaPorNomeRequestBody();
            inValue.Body.nome = nome;
            return ((ClienteAsmx.ServicoDeDados.PessoasServiceSoap)(this)).ObterPessoaPorNomeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteAsmx.ServicoDeDados.ObterNomePessoaEmMaiusculoResponse ClienteAsmx.ServicoDeDados.PessoasServiceSoap.ObterNomePessoaEmMaiusculo(ClienteAsmx.ServicoDeDados.ObterNomePessoaEmMaiusculoRequest request) {
            return base.Channel.ObterNomePessoaEmMaiusculo(request);
        }
        
        public ClienteAsmx.ServicoDeDados.Pessoa ObterNomePessoaEmMaiusculo(ClienteAsmx.ServicoDeDados.Pessoa pessoa) {
            ClienteAsmx.ServicoDeDados.ObterNomePessoaEmMaiusculoRequest inValue = new ClienteAsmx.ServicoDeDados.ObterNomePessoaEmMaiusculoRequest();
            inValue.Body = new ClienteAsmx.ServicoDeDados.ObterNomePessoaEmMaiusculoRequestBody();
            inValue.Body.pessoa = pessoa;
            ClienteAsmx.ServicoDeDados.ObterNomePessoaEmMaiusculoResponse retVal = ((ClienteAsmx.ServicoDeDados.PessoasServiceSoap)(this)).ObterNomePessoaEmMaiusculo(inValue);
            return retVal.Body.ObterNomePessoaEmMaiusculoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteAsmx.ServicoDeDados.ObterNomePessoaEmMaiusculoResponse> ClienteAsmx.ServicoDeDados.PessoasServiceSoap.ObterNomePessoaEmMaiusculoAsync(ClienteAsmx.ServicoDeDados.ObterNomePessoaEmMaiusculoRequest request) {
            return base.Channel.ObterNomePessoaEmMaiusculoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteAsmx.ServicoDeDados.ObterNomePessoaEmMaiusculoResponse> ObterNomePessoaEmMaiusculoAsync(ClienteAsmx.ServicoDeDados.Pessoa pessoa) {
            ClienteAsmx.ServicoDeDados.ObterNomePessoaEmMaiusculoRequest inValue = new ClienteAsmx.ServicoDeDados.ObterNomePessoaEmMaiusculoRequest();
            inValue.Body = new ClienteAsmx.ServicoDeDados.ObterNomePessoaEmMaiusculoRequestBody();
            inValue.Body.pessoa = pessoa;
            return ((ClienteAsmx.ServicoDeDados.PessoasServiceSoap)(this)).ObterNomePessoaEmMaiusculoAsync(inValue);
        }
    }
}
